from datetime import date
from typing import Protocol

from arbeitszeit.domain.entities import (
    AuditLogEntry,
    Employee,
    ReviewCase,
    RfidCard,
    TimeBooking,
    WorkScheduleVersion,
)
from arbeitszeit.domain.enums import BookingStatus


class EmployeeRepository(Protocol):
    def get_by_id(self, employee_id: int) -> Employee | None: ...
    def get_active_by_personnel_no(self, personnel_no: str) -> Employee | None: ...


class RfidCardRepository(Protocol):
    def get_active_by_uid(self, uid_hash: str) -> RfidCard | None: ...
    def get_by_id(self, card_id: int) -> RfidCard | None: ...


class TimeBookingRepository(Protocol):
    def add(self, booking: TimeBooking) -> TimeBooking: ...
    def get_by_id(self, booking_id: int) -> TimeBooking | None: ...
    def list_for_employee_on_day(self, employee_id: int, day: date) -> list[TimeBooking]: ...
    def list_open_for_employee(self, employee_id: int) -> list[TimeBooking]: ...
    def update_status(self, booking_id: int, status: BookingStatus) -> None: ...


class WorkScheduleRepository(Protocol):
    def get_effective(self, weekday: int, on_date: date) -> WorkScheduleVersion | None: ...
    def list_versions(self, weekday: int) -> list[WorkScheduleVersion]: ...


class ReviewCaseRepository(Protocol):
    def add(self, case: ReviewCase) -> ReviewCase: ...
    def list_open_for_employee(self, employee_id: int) -> list[ReviewCase]: ...
    def close(self, case_id: int, resolved_by_user_id: int) -> None: ...


class AuditLogRepository(Protocol):
    def add(self, entry: AuditLogEntry) -> AuditLogEntry: ...


class SystemConfigRepository(Protocol):
    def get_current(self, config_key: str) -> str | None: ...
