from datetime import date, datetime
from typing import Literal, Protocol

from arbeitszeit.domain.entities import (
    AuditLogEntry,
    BookingCorrection,
    Employee,
    ReviewCase,
    RfidCard,
    Supplement,
    TimeBooking,
    UserAccount,
    WorkScheduleVersion,
)
from arbeitszeit.domain.enums import BookingStatus, ChangeOrigin, ReviewCaseStatus


class EmployeeRepository(Protocol):
    def get_by_id(self, employee_id: int) -> Employee | None: ...
    def get_active_by_personnel_no(self, personnel_no: str) -> Employee | None: ...


class UserAccountRepository(Protocol):
    def get_by_id(self, user_id: int) -> UserAccount | None: ...
    def get_by_username(self, username: str) -> UserAccount | None: ...


class RfidCardRepository(Protocol):
    def get_active_by_uid_hash(self, uid_hash: str) -> RfidCard | None: ...
    def get_by_id(self, card_id: int) -> RfidCard | None: ...


class TimeBookingRepository(Protocol):
    def add(self, booking: TimeBooking) -> TimeBooking: ...
    def get_by_id(self, booking_id: int) -> TimeBooking | None: ...
    def list_for_employee_on_day(self, employee_id: int, day: date) -> list[TimeBooking]: ...
    def list_open_for_employee(self, employee_id: int) -> list[TimeBooking]: ...
    def list_between(self, employee_id: int, from_dt: datetime, to_dt: datetime) -> list[TimeBooking]: ...
    def update_status(self, booking_id: int, status: BookingStatus) -> None: ...


class WorkScheduleRepository(Protocol):
    def get_effective(self, weekday: int, on_date: date, employee_id: int | None = None) -> WorkScheduleVersion | None: ...
    def list_versions(self, weekday: int | None = None, scope_employee_id: int | None = None) -> list[WorkScheduleVersion]: ...


class ReviewCaseRepository(Protocol):
    def add(self, case: ReviewCase) -> ReviewCase: ...
    def list_open_for_employee(self, employee_id: int) -> list[ReviewCase]: ...
    def resolve(
        self,
        case_id: int,
        status: Literal[ReviewCaseStatus.RESOLVED, ReviewCaseStatus.CLOSED_WITH_NOTE],
        closed_by_user_id: int,
        note: str | None = None,
    ) -> None: ...


class SupplementRepository(Protocol):
    def add(self, supplement: Supplement) -> Supplement: ...
    def get_by_id(self, supplement_id: int) -> Supplement | None: ...
    def list_pending(self) -> list[Supplement]: ...
    def approve(self, supplement_id: int, approved_by_user_id: int, approved_at: datetime) -> None: ...
    def reject(self, supplement_id: int, rejected_by_user_id: int, rejected_at: datetime) -> None: ...


class BookingCorrectionRepository(Protocol):
    def add(self, correction: BookingCorrection) -> BookingCorrection: ...
    def list_for_booking(self, booking_id: int) -> list[BookingCorrection]: ...


class AuditLogRepository(Protocol):
    def add(self, entry: AuditLogEntry) -> AuditLogEntry: ...


class SystemConfigRepository(Protocol):
    def get_current(self, config_key: str) -> str | None: ...
    def set_current(
        self,
        config_key: str,
        value_json: str,
        change_origin: ChangeOrigin,
        changed_by_user_id: int | None,
        changed_at: datetime,
        reason: str | None = None,
    ) -> None: ...
