from enum import StrEnum


class BookingType(StrEnum):
    COME = "COME"
    GO = "GO"
    BREAK_START = "BREAK_START"
    BREAK_END = "BREAK_END"


class BookingStatus(StrEnum):
    OK = "OK"
    OPEN = "OPEN"
    WARN = "WARN"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    CORRECTED = "CORRECTED"
    CLOSED_WITH_NOTE = "CLOSED_WITH_NOTE"
    POSSIBLE_BREAK_VIOLATION = "POSSIBLE_BREAK_VIOLATION"
    POSSIBLE_REST_VIOLATION = "POSSIBLE_REST_VIOLATION"
    POSSIBLE_MAX_HOURS_VIOLATION = "POSSIBLE_MAX_HOURS_VIOLATION"
    MANUAL_ENTRY = "MANUAL_ENTRY"


class ReviewCaseType(StrEnum):
    OPEN_WORK_PHASE = "OPEN_WORK_PHASE"
    OPEN_BREAK_PHASE = "OPEN_BREAK_PHASE"
    OUTSIDE_SCHEDULE_WINDOW = "OUTSIDE_SCHEDULE_WINDOW"
    POSSIBLE_BREAK_VIOLATION = "POSSIBLE_BREAK_VIOLATION"
    POSSIBLE_REST_VIOLATION = "POSSIBLE_REST_VIOLATION"
    POSSIBLE_MAX_HOURS_VIOLATION = "POSSIBLE_MAX_HOURS_VIOLATION"
    IMPLAUSIBLE_SEQUENCE = "IMPLAUSIBLE_SEQUENCE"
    UNKNOWN_CARD_ATTEMPT = "UNKNOWN_CARD_ATTEMPT"
    INACTIVE_CARD_ATTEMPT = "INACTIVE_CARD_ATTEMPT"
    TIME_ANOMALY = "TIME_ANOMALY"
    MANUAL_ENTRY_REVIEW = "MANUAL_ENTRY_REVIEW"


class ReviewCaseStatus(StrEnum):
    OPEN = "OPEN"
    IN_REVIEW = "IN_REVIEW"
    RESOLVED = "RESOLVED"
    CLOSED_WITH_NOTE = "CLOSED_WITH_NOTE"


class ReviewSeverity(StrEnum):
    INFO = "INFO"
    WARN = "WARN"
    CRITICAL = "CRITICAL"


class CardStatus(StrEnum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    REPLACED = "REPLACED"
    LOST = "LOST"


class UserRole(StrEnum):
    EMPLOYEE = "EMPLOYEE"
    ADMIN = "ADMIN"
    REVIEWER = "REVIEWER"
    TECH = "TECH"


class BookingSource(StrEnum):
    TERMINAL = "TERMINAL"
    MANUAL = "MANUAL"
    IMPORT = "IMPORT"


class ChangeOrigin(StrEnum):
    SYSTEM_SEED = "SYSTEM_SEED"
    ADMIN_UI = "ADMIN_UI"
    MIGRATION = "MIGRATION"


class ApprovalStatus(StrEnum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class ScopeType(StrEnum):
    GLOBAL = "GLOBAL"
    EMPLOYEE = "EMPLOYEE"
